### ISSUE TITLE
Documentation bug (camelCase vs snake_case)

### ISSUE THREAD

**Issue by codyebberson** [jgroups-extras/jgroups-aws#2]
There are two examples in the README that use camelCase for attribute names:

```xml
<org.jgroups.aws.s3.NATIVE_S3_PING
        regionName="us-east-1a"
        bucketName="jgroups-s3-test" />
```

This syntax caused errors for me:

```
java.lang.IllegalArgumentException: JGRP000001: configuration error: the following properties in org.jgroups.aws.s3.NATIVE_S3_PING are not recognized: {bucketName=..., bucketPrefix=..., regionName=...}
	at org.jgroups.stack.Configurator.createLayer(Configurator.java:278)
	at org.jgroups.stack.Configurator.createProtocols(Configurator.java:215)
	at org.jgroups.stack.Configurator.setupProtocolStack(Configurator.java:82)
	at org.jgroups.stack.Configurator.setupProtocolStack(Configurator.java:49)
	at org.jgroups.stack.ProtocolStack.setup(ProtocolStack.java:475)
	at org.jgroups.JChannel.init(JChannel.java:989)
	at org.jgroups.JChannel.<init>(JChannel.java:148)
	at org.jgroups.JChannel.<init>(JChannel.java:130)
```

After stepping through the code, I realized that the NATIVE_S3_PING class expects the XML attributes to be in snake_case format:

```xml
<org.jgroups.aws.s3.NATIVE_S3_PING
        region_name="us-east-1a"
        bucket_name="jgroups-s3-test" />
```

After that, everything worked great.

**Comment by belaban** [comment]
Thanks for pointing this out, Cody! Fixed
