### ISSUE TITLE
Unable to load AWS credentials from any provider in the chain. 

### ISSUE THREAD

**Issue by mogarg** [jgroups-extras/jgroups-aws#3]
```
Where do I provide the access key and secret key since I am getting the following error?

Exception in thread "main" com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1119)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:759)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:723)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4185)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4132)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1302)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1259)
	at org.jgroups.aws.s3.NATIVE_S3_PING.init(NATIVE_S3_PING.java:88)
	at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:840)
	at org.jgroups.stack.ProtocolStack.setup(ProtocolStack.java:479)
	at org.jgroups.JChannel.init(JChannel.java:992)
```

**Comment by mogarg** [comment]
Just specified the credentials under ~/.aws/credentials in the format 

```
[default]
aws_access_key_id=AWS_ACCESS_KEY
aws_secret_access_key=AWS_SECRET_ACCESS_KEY
```
