### ISSUE TITLE
jgroups-aws with Keycloak `22.0.3` - problem with RELAY

### ISSUE THREAD

**Issue by swc-hannes** [jgroups-extras/jgroups-aws#315]
We tried to upgrade Keycloak from `22.0.5` (where we still used aws-jgroups `2.0.1.Final`) to `23.0.4`. We run keycloak in FARGATE containers using S3 as backend, utilizing `3.0.0.Final` now. Keycloak 23 now does not come up complaining about infinispan configuration. The problem also occurs with `2.0.1.Final`.

**This is what the logs give us:**
```
2024-01-12 08:48:24,545 ERROR [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheConfigurationException: ISPN000659: Component ComponentWrapper{name=org.infinispan.remoting.transport.Transport, instance=org.infinispan.remoting.transport.jgroups.JGroupsTransport@7fa49d39, status=FAILED} failed to start
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:584)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
	at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:43)
	at org.infinispan.metrics.impl.CorePackageImpl$3.start(CorePackageImpl.java:78)
	at org.infinispan.metrics.impl.CorePackageImpl$3.start(CorePackageImpl.java:70)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:379)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:252)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:779)
	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:747)
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:411)
	at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:96)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.BootstrapMethodError: bootstrap method initialization exception
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:485)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:63)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:49)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
	... 22 more
Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type class org.jgroups.protocols.relay.RELAY2; not a subtype of implementation type class org.jgroups.protocols.relay.RELAY
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:273)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:340)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:134)
	... 31 more
```

We are creating this bundle and put it into `providers/`:

```
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.group</groupId>
    <artifactId>s3-native-ping-bundle</artifactId>
    <version>1</version>

    <properties>
        <aws.sdk.version>1.12.410</aws.sdk.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-core</artifactId>
                <version>${aws.sdk.version}</version>
            </dependency>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-s3</artifactId>
                <version>${aws.sdk.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.jgroups.aws</groupId>
            <artifactId>jgroups-aws</artifactId>
            <version>3.0.0.Final</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <id>copy-deps</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

Thank you in advance for any hint.

**Comment by rhusar** [comment]
Hello @swc-hannes, nothing in the stack trace is indicating problem with jgroups-aws, but I think I see what's going on: by doing provisioning in the fashion you have done it, you are provisioning all of these project's dependencies, namely:

https://github.com/jgroups-extras/jgroups-aws/blob/main/pom.xml#L136-L153

which I assume means you have now jgroups-xyz.jar twice on the classpath, which won't work. Ensure you have only the correct version of jgroups on CP, the one shipping with the project you are using.

**Comment by rhusar** [comment]
I have opened https://github.com/jgroups-extras/jgroups-aws/issues/305 to improve the instructions since there have been multiple questions around this...

**Comment by swc-hannes** [comment]
> Hello @swc-hannes, nothing in the stack trace is indicating problem with jgroups-aws, but I think I see what's going on: by doing provisioning in the fashion you have done it, you are provisioning all of these project's dependencies, namely:
> 
> https://github.com/jgroups-extras/jgroups-aws/blob/main/pom.xml#L136-L153
> 
> which I assume means you have now jgroups-xyz.jar twice on the classpath, which won't work. Ensure you have only the correct version of jgroups on CP, the one shipping with the project you are using.

indeed - i excluded jgroups from my bundle and it worked. Thanks a lot!

**Comment by rhusar** [comment]
> > Hello @swc-hannes, nothing in the stack trace is indicating problem with jgroups-aws, but I think I see what's going on: by doing provisioning in the fashion you have done it, you are provisioning all of these project's dependencies, namely:
> > https://github.com/jgroups-extras/jgroups-aws/blob/main/pom.xml#L136-L153
> > which I assume means you have now jgroups-xyz.jar twice on the classpath, which won't work. Ensure you have only the correct version of jgroups on CP, the one shipping with the project you are using.
> 
> indeed - i excluded jgroups from my bundle and it worked. Thanks a lot!

Awesome, glad it worked.

**Comment by duffybelfield** [comment]
@swc-hannes I'm getting the same issue, how did you exclude from your bundle?

Here is my pom.xml

```<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.group</groupId>
    <artifactId>s3-native-ping-bundle</artifactId>
    <version>1</version>
    <dependencies>
        <dependency>
            <groupId>org.jgroups.aws</groupId>
            <artifactId>jgroups-aws</artifactId>
            <version>3.0.0.Final</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <id>copy-deps</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by swc-hannes** [comment]
hey, here's mine:

```
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.group</groupId>
    <artifactId>s3-native-ping-bundle</artifactId>
    <version>1</version>

    <properties>
        <aws.sdk.version>1.12.636</aws.sdk.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-core</artifactId>
                <version>${aws.sdk.version}</version>
            </dependency>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-s3</artifactId>
                <version>${aws.sdk.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.jgroups.aws</groupId>
            <artifactId>jgroups-aws</artifactId>
            <version>3.0.0.Final</version>
            <exclusions>
                <!--
                    excluding jgroups because already
                    in keycloak
                 -->
                <exclusion>
                    <groupId>org.jgroups</groupId>
                    <artifactId>jgroups</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <id>copy-deps</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

```

**Comment by duffybelfield** [comment]
@swc-hannes could you supply your Dockerfile as well? I'm so close, but so far away haha

**Comment by swc-hannes** [comment]
yes, basically it's this, ... but i think it's a bit off this topic.

```
ARG version=25.0.1
FROM public.ecr.aws/docker/library/maven:3.8.6-openjdk-18-slim as maven-builder
COPY native-s3-ping/pom.xml ./
RUN mvn package

FROM alpine:latest as awscli-builder
RUN apk add --no-cache curl \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ls /usr/lib/

FROM amazon/aws-cli as zlib-builder
RUN mkdir /tmp/lib64 \
    && cp /usr/lib64/libz.so.1 /tmp/lib64/

FROM quay.io/keycloak/keycloak:$version as keycloak-builder
COPY --from=maven-builder --chown=keycloak target/s3*dep*.jar /opt/keycloak/providers/
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_DB=postgres

# Build keycloak
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:$version
COPY --from=keycloak-builder /opt/keycloak/ /opt/keycloak/
COPY --from=awscli-builder /aws /aws
COPY --from=zlib-builder /tmp/lib64/libz.so.1 /usr/lib64/
ENV KC_CACHE=ispn
ENV KC_CACHE_STACK=ec2
# install awscli
USER root
RUN ./aws/install
USER keycloak
WORKDIR /opt/keycloak
RUN keytool .... (line from official doc)
ENTRYPOINT ["/opt/keycloak/bin/kc.sh","start","--optimized"]
```
